version: "3.7"
services:
  hadoop-hive:
    build: ./images/hadoop_hive
    container_name: hadoop-hive
    hostname: hadoop-hive
    ports:
      - "8088:8088" # ResourceManager
      - "9864:9864" # DataNode WebUI
      - "9870:9870" # HDFS / WebHDFS
      - "8032:8032" # ResourceManager
      - "11000:10000" # HiveServer2 - Binary Mode
      - "11001:10001" # HiveServer - HTTP Mode
      - "11002:10002" # Hiveserver WebUI
    depends_on:
      - postgres
    networks:
      - data-master
  superset:
    build: ./images/superset
    container_name: superset
    hostname: superset
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - data-master

  postgres:
    image: postgres:12.1-alpine
    container_name: postgres
    hostname: postgres
    volumes:
      - pg_data:/var/lib/postgresl/data/
      - ./images/postgresql/scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    env_file:
      - ./images/postgresql/db.env
    networks:
      - data-master
  
  hue:
    image: gethue/hue
    container_name: hue
    hostname: hue
    ports:
      - "8888:8888"
    volumes:
      - ./images/hue/hue-overrides.ini:/usr/share/hue/desktop/conf/hue-overrides.ini
    depends_on:
      - postgres
      - hadoop-hive
    networks:
      - data-master

  apicurio:
    image: apicurio/apicurio-registry-sql
    container_name: apicurio
    hostname: apicurio
    ports:
      - "8080:8085"
    env_file:
      - ./images/apicurio/confs.env
    depends_on:
      - postgres
    networks:
      - data-master
  zookeeper:
    image: confluentinc/cp-zookeeper:6.2.0
    restart: always
    container_name: zookeeper
    networks: 
      - data-master
    env_file:
      - ./images/kafka/zookeeper.env


  kafka:
    image: confluentinc/cp-kafka:6.2.0
    restart: always
    container_name: kafka
    networks: 
      - data-master
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    env_file:
      - ./images/kafka/kafka.env

networks:
  data-master:
    driver: bridge
    

volumes:
  pg_data: